services:
  db:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: db_praktikum
    volumes:
      - db_data:/var/lib/mysql
      - ./db_praktikum.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  server:
    build: ./server
    restart: always
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: secret
      DB_NAME: db_praktikum
      MAIL_USER: emailkamu@gmail.com   # ← tambah ini
      MAIL_PASS: xxxx xxxx xxxx xxxx   # ← Gmail App Password
    depends_on:
      - db
    networks:
      - app_network

  client:
    build: ./client
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl/certs/server.crt:/etc/ssl/certs/server.crt
      - /etc/ssl/private/server.key:/etc/ssl/private/server.key
      - /etc/ssl/certs/ca-chain.crt:/etc/ssl/certs/ca-chain.crt
    depends_on:
      - server
      - client
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
