server {
    listen 80;
    server_name aplikasi.local;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name aplikasi.local;

    ssl_certificate     /etc/ssl/certs/server.crt;
    ssl_certificate_key /etc/ssl/private/server.key;
    ssl_trusted_certificate /etc/ssl/certs/ca-chain.crt;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://client:80;
    }

    location /api {
        proxy_pass http://server:3001;
    }
}

